config/routes.rb
Rails.application.routes.draw do
  root "home#index", as: :home
  get "/blog", to: "home#blog", as: :blog
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
  def blog; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/blog.html.erb
<% content_for :body do %>
    <h1>Blog</h1>
    <h5>Some of my thoughts, <s>written</s> printed on <s>paper</s> screen</h5>

    <hr>
<% end %>

<%= render template: 'layouts/base' %>

app/views/home/index.html.erb
<% content_for :body do %>
  <h1>Matthew Sutanto</h1>
  <h5>Software Engineer</h5>

  <hr>

  <p>I am a software engineer based in Indonesia. I'm available for remote
    full-time or part-time jobs in most timezones (including European/American
    time).</p>

  <p>My main specialty is backend development. However, I'm open for other
    software development areas, such as: mobile app or full-stack web
    development.</p>

  <p>Having low-level development interest, I have a keen eye for performance in
    every piece of code I write.</p>

  <p>While developing any product, I'm not just blindly executing instructions
    and write code as I'm told to. I like to think of the product as my own
    while making decisions for it. If something is not right or might cause
    problems later, I will bring that up in meetings and discussions. Because
    in every work that I do, I believe in the product I'm working on.</p>

  <p>My main programming languages (you can count me on these):</p>
  <ul>
    <li>Go</li>
    <li>Python</li>
    <li>PHP</li>
    <li>Java</li>
    <li>Dart (& Flutter!)</li>
  </ul>

  <p>Other skillsets:</p>
  <ul>
    <li>HTML, CSS, and JS for web frontends.</li>
    <li>General SQL database usage (DML, DDL)</li>
    <li>Configuring servers to work (Nginx, Docker, etc)</li>
  </ul>

<% end %>

<%= render template: "layouts/base" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title or "Title" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= yield :head %>
  </head>

  <body data-controller="app" data-bs-theme="dark">
    <div class="container-fluid px-0">
      <button
        data-app-target="themeToggler"
        id="theme-toggler"
        class="btn btn-secondary rounded-circle"
        data-action="click->app#toggleTheme"
      ><i class="fas fa-moon"></i></button>
      <%= yield :navbar %>

      <div class="col-sm-8 col-md-6 col-10 mx-auto py-3">
      <%= yield :body %>
      </div>
    </div>
  </body>

  <%= yield :scripts %>
</html>

app/views/layouts/base.html.erb
<% content_for :navbar do %>
    <nav class="d-flex justify-content-center">
      <a class="mx-3 p-3" href="<%= home_url %>">Home</a>
      <a class="mx-3 p-3" href="#">Docs</a>
      <a class="mx-3 p-3" href="<%= blog_url %>">Blog</a>
      <a class="mx-3 p-3" href="#">Projects</a>
      <a class="mx-3 p-3" href="#">GitHub</a>
    </nav>
<% end %>

<%= render template: "layouts/application" %>